### ISSUE TITLE
An error occurred while trying to deserialize evtx stream

### ISSUE THREAD

**Issue by AhmetPayaslioglu** [WithSecureLabs/chainsaw#208]
Hi,

Thank you for this project. I have a some issue on sigma execution.

I used 2.10.3 version in Windows.

My command line was:

chainsaw_x86_64-pc-windows-msvc.exe hunt C:\Users\test\Desktop\testlogs -s sigma/ --mapping mappings/sigma-event-logs-all.yml --output ./output.csv

When I executed above command, I saw this error. 

[+] Loading detection rules from: sigma/
[!] Loaded 3353 detection rules (490 not loaded)
[+] Loading forensic artefacts from: C:\Users\test\Desktop\testlogs  (extensions: .evtx, .evt)
[+] Loaded 174 forensic artefacts (1066.8 MB)
[x] Failed to hunt through file 'C:\Users\test\Desktop\testlogs\winevt\logs\Microsoft-Windows-WMI-Activity%4Operational.evtx' - An error occurred while trying to deserialize evtx stream. in C:\Users\test\Desktop\testlogs\winevt\logs\Microsoft-Windows-WMI-Activity%4Operational.evtx

But if I delete only this log (C:\Users\test\Desktop\testlogs\winevt\logs\Microsoft-Windows-WMI-Activity%4Operational.evtx) , then other logs executed and finished succesfully. What is the problem with VMI?

Thanks.

**Comment by FranticTyping** [comment]
Hi @AhmetPayaslioglu 

Without seeing the event log it's difficult to determine why that WMI evtx file is causing issues. I assume it's just a single record in that event log which is causing the error though.

Instead of deleting the whole evtx file, you can use the `--skip-errors` flag which will allow Chainsaw to continue processing the file and just skip over the problematic record. 

Thanks

**Comment by FranticTyping** [comment]
This does remind me that we should highlight the `--skip-errors` flag when chainsaw bails. Let me do that now.

**Comment by FranticTyping** [comment]
Added the help message in #209 

I'll close this issue for now, but happy to re-open if you have more questions.
